# Generated by Django 4.0.2 on 2023-10-23 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('nationality', models.CharField(max_length=50)),
                ('occupation', models.CharField(choices=[('Job', 'Job'), ('Business', 'Business'), ('Student', 'Student'), ('Housewife', 'Housewife'), ('Others', 'Others')], max_length=90)),
                ('company', models.CharField(max_length=40)),
                ('company_job', models.CharField(max_length=40)),
                ('dependent_passport', models.FileField(upload_to='depenedent')),
                ('institute', models.CharField(max_length=40)),
                ('dependent_visa', models.FileField(upload_to='depenedent')),
                ('occupation_details', models.TextField()),
                ('visa_status', models.CharField(choices=[('Permit', 'Permit'), ('Visit Visa', 'Visit Visa'), ('Temporary Permit', 'Temporary Permit'), ('Other', 'Other')], max_length=20)),
                ('visa_expiry_date', models.CharField(max_length=43)),
                ('living_in_rwanda', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('relationship', models.CharField(blank=True, max_length=34, null=True)),
                ('dob', models.CharField(blank=True, max_length=44, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=40)),
                ('school_name', models.CharField(blank=True, max_length=90, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('job_name', models.CharField(blank=True, max_length=50, null=True)),
                ('job_details', models.TextField(blank=True, null=True)),
                ('job_company', models.CharField(blank=True, max_length=60, null=True)),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('company_details', models.CharField(blank=True, max_length=50, null=True)),
                ('business_type', models.CharField(blank=True, max_length=50, null=True)),
                ('buisness_details', models.TextField(blank=True, max_length=800, null=True)),
                ('occupation', models.CharField(choices=[('Job', 'Job'), ('Business', 'Business'), ('Student', 'Student'), ('Housewife', 'Housewife'), ('Others', 'Others')], max_length=10)),
                ('passport_picture', models.ImageField(blank=True, null=True, upload_to='passport_pictures/')),
                ('occupation_details', models.TextField(blank=True, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('passport_expiry', models.CharField(blank=True, max_length=33, null=True)),
                ('proof_of_origin', models.CharField(blank=True, choices=[('NIC', 'NIC'), ('POC', 'POC'), ('Other', 'Other')], max_length=10, null=True)),
                ('origin_id_number', models.CharField(blank=True, max_length=20, null=True)),
                ('visa_document', models.FileField(blank=True, null=True, upload_to='')),
                ('visa_status', models.CharField(blank=True, choices=[('Permit', 'Permit'), ('Visit Visa', 'Visit Visa'), ('Temporary Permit', 'Temporary Permit'), ('Other', 'Other')], max_length=20, null=True)),
                ('visa_expiry_date', models.CharField(blank=True, max_length=43, null=True)),
                ('staying_in_rwanda_since', models.CharField(blank=True, max_length=33, null=True)),
                ('living_with_dependents', models.BooleanField(default=False)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address_in_rwanda', models.CharField(blank=True, max_length=50, null=True)),
                ('province', models.CharField(blank=True, max_length=40, null=True)),
                ('district', models.CharField(blank=True, max_length=40, null=True)),
                ('sector', models.CharField(blank=True, max_length=40, null=True)),
                ('cell', models.CharField(blank=True, max_length=40, null=True)),
                ('emergency_country', models.CharField(blank=True, max_length=50, null=True)),
                ('emergency_mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('other_full_address', models.CharField(blank=True, max_length=60, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('relation', models.CharField(blank=True, max_length=40, null=True)),
                ('status', models.CharField(choices=[('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('PENDING', 'PENDING')], default='PENDING', max_length=20)),
                ('dependents', models.ManyToManyField(blank=True, related_name='dependents_of_registration', to='main.Dependent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dependent',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.registration'),
        ),
    ]
