# Generated by Django 4.0.2 on 2023-10-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_registration_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='visa_document',
            field=models.FileField(blank=True, null=True, upload_to='visa_doc/'),
        ),
    ]
