# Generated by Django 4.0.2 on 2023-10-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_registration_contact_name_alter_registration_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='occupation',
            field=models.CharField(choices=[('Job', 'Job'), ('Business', 'Business'), ('Student', 'Student'), ('Housewife', 'Housewife'), ('Others', 'Others')], max_length=10),
        ),
    ]
